# Generated by Django 5.2.15 on 2026-07-08 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0035_user_is_spam"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        help_text="Type of post: cfp, speaker, session, ticket, schedule, custom",
                        max_length=30,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of linked entity (e.g. submission PK, speaker PK)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="Target date and time for publication"
                    ),
                ),
                ("post_text", models.TextField(help_text="Social media copy")),
                (
                    "offset_days",
                    models.IntegerField(
                        default=0,
                        help_text="Offset days or minutes used during generation",
                    ),
                ),
                (
                    "template_context",
                    models.CharField(
                        default="default",
                        help_text="Template context key e.g. announcement, reminder",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("exported", "Exported"),
                            ("excluded", "Excluded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="True if manually locked or custom added by organizer",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_posts",
                        to="base.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Post",
                "verbose_name_plural": "Social Media Posts",
                "ordering": ["scheduled_at"],
                "unique_together": {("event", "post_type", "entity_id", "offset_days")},
            },
        ),
    ]
