# Generated by Django 5.2.15 on 2026-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                    ("exported", "Exported"),
                    ("excluded", "Excluded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
