# Generated by Django 5.2.15 on 2026-07-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0043_remove_sendmail_from_plugins"),
        ("socialmedia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mastodon", "Mastodon"),
                            ("telegram", "Telegram"),
                            ("twitter", "Twitter / X"),
                            ("linkedin", "LinkedIn"),
                            ("postiz", "Postiz"),
                            ("buffer", "Buffer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform_username",
                    models.CharField(
                        help_text="e.g. channel ID, username handle, or scheduler workspace name",
                        max_length=255,
                    ),
                ),
                (
                    "encrypted_credentials",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fernet-encrypted JSON credentials blob",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True if this integration connection is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_accounts",
                        to="base.organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Account",
                "verbose_name_plural": "Social Media Accounts",
                "unique_together": {("organizer", "provider", "platform_username")},
            },
        ),
    ]
