# Generated by Django 5.2.16 on 2026-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0002_socialmediaaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error logs or failure reason returned by the provider API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the media/image attachment (e.g. speaker avatar)",
                max_length=1024,
                null=True,
            ),
        ),
    ]
