# Generated by Django 5.2.16 on 2026-08-31 09:15

from django.db import migrations, models


def cleanup_legacy_scheduler_data(apps, schema_editor):
    SocialMediaAccount = apps.get_model("socialmedia", "SocialMediaAccount")
    SocialMediaPost = apps.get_model("socialmedia", "SocialMediaPost")

    # Delete or deactivate leftover Postiz / Buffer accounts
    SocialMediaAccount.objects.filter(provider__in=["postiz", "buffer"]).delete()

    # Move any legacy scheduled posts to EXPORTED so they won't be dispatched natively
    SocialMediaPost.objects.filter(
        status="scheduled", entity_id__endswith="_postiz"
    ).update(status="exported")
    SocialMediaPost.objects.filter(
        status="scheduled", entity_id__endswith="_buffer"
    ).update(status="exported")


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0003_socialmediapost_error_message_and_more"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_legacy_scheduler_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("mastodon", "Mastodon"),
                    ("telegram", "Telegram"),
                    ("twitter", "Twitter / X"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
            ),
        ),
    ]
