# Generated by Django 5.2.16 on 2026-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0004_alter_socialmediaaccount_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="platform_username",
            field=models.CharField(
                help_text="e.g. channel ID or username handle",
                max_length=255,
            ),
        ),
    ]
